### ISSUE TITLE
Missing url!

### ISSUE THREAD

**Issue by ahmedmohiduet** [28msec/xbrl-tutorial#14]
I am trying urls for retriveing filing information info from document:
urls:
http://secxbrl.xbrl.io/api/filings.jq?cik=320193&cik=1288776
http://secxbrl.xbrl.io/api/filings.jq?cik=320193&fiscalYear=2012&fiscalPeriod=Q1&fiscalPeriod=Q2

But they all returned 'page not found'.

Am I missing something!

**Comment by wcandillon** [comment]
@ahmedmohiduet This tutorial is deprecated. If you are interested to query sec filings please refer to the documentation at http://app.secxbrl.info/. Please feel free to reopen this issue if you have any further questions.
